# Generated by Django 5.2 on 2026-01-15 21:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('timezone', models.CharField(max_length=100, verbose_name='time zone')),
            ],
            options={
                'verbose_name': 'geography',
                'verbose_name_plural': 'geographies',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('surname', models.CharField(max_length=32)),
                ('given_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('date_of_birth', models.DateField()),
                ('sin', models.CharField(blank=True, max_length=11, verbose_name='SIN')),
                ('date_hired', models.DateField(default=django.utils.timezone.localdate)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=128, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=128, verbose_name='Address line 2')),
                ('postal_code', models.CharField(max_length=7)),
                ('phone_number', models.CharField(max_length=12)),
                ('extra_phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('emergency_phone_number', models.CharField(blank=True, max_length=12)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=64)),
                ('iss_iat_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ISS/IAT ID')),
                ('mss_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='MSS ID')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('iss_security_license_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='ISS Security License Number')),
                ('iat_security_license_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='IAT Security License Number')),
                ('mss_security_license_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='MSS Security License Number')),
                ('notes', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='c4dce8', max_length=6)),
                ('weekly_hours', models.PositiveSmallIntegerField(default=0, help_text='The number of hours this employee works per week')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='misc.city')),
                ('emergency_relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='misc.relationship', verbose_name='Relationship')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.geography', verbose_name='geography')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
