# Generated by Django 5.2 on 2026-01-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='given_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname',
        ),
    ]
