# Generated by Django 5.2 on 2026-01-16 00:16

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_given_name_remove_employee_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sin_e',
            field=encrypted_fields.fields.EncryptedCharField(max_length=120, null=True, verbose_name='SIN(e)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
