# Generated by Django 5.2 on 2026-01-16 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_sin_e_alter_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
    ]
